version: '3.4'

services:
    golang.dev:
        container_name: golang.dev
        build: .
        ports:
            - "3000:3000"
        environment:
            user: $user
            group: $group
        volumes:
            - "${PWD}/src:/app"