version: '3.4'

services:
    golang.dev:
        container_name: golang.dev
        build:
            context: .
            target: golang_dev
        environment:
            user: $user
            group: $group
        #command: /go/entrypoint.sh
        #entrypoint: /go/entrypoint.sh
        #command: $entrypoint
        command: bash -c "${entrypoint}"
        #command: "echo ${entrypoint}"
        #command: ls -la
        networks:
            - golang.dev
        volumes:
            - "${PWD}:/go"
        ports:
            - "3000:3000"
networks:
    golang.dev:
        driver: bridge