version: '3.4'

services:
    golang.dev:
        container_name: golang.dev
        build:
            context: .
            target: golang_dev
        environment:
            user: $user
            group: $group
        networks:
            - golang.dev
        volumes:
            - "${PWD}/src:/go/src"
        ports:
            - "3000:3000"
networks:
    golang.dev:
        driver: bridge