version: '3'
services:
  dev-zookeeper:
    container_name:   dev-zookeeper
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  dev-kafka:
    container_name: dev-kafka
    hostname: dev-kafka
    image: wurstmeister/kafka
    depends_on:
      -   dev-zookeeper
    ports:
      - "9092:9092"
    expose:
      - "9093"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://:9093,OUTSIDE://:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://:9093,OUTSIDE://:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: dev-zookeeper:2181
      KAFKA_CREATE_TOPICS: "test:1:1"
  kafka-ui.dev:
    container_name: dev-kafka-ui
    image: quay.io/cloudhut/kowl:master
    ports:
      - "8086:8080"
    depends_on:
      -   dev-kafka
    environment:
      KAFKA_BROKERS=host.docker.internal:9092:
