version: '3'
services:
  percona.xstack:
    container_name: percona.xstack
    image: perconalab/percona-server:8.0.34-26.1-aarch64
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '33061:3306'
    volumes:
      - db-data:/var/lib/mysql # store data to local machine
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql # need unmount volumes (docker-compose down -v) to reinitialize
      - ./my.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf

volumes:
  db-data:
