version: '3'
services:
    mysql-5.7:
        container_name: mysql-5.7
        image: library/mysql:5.7
        ports:
            - 3357:3357
        environment:
            MYSQL_ROOT_PASSWORD: 12345
            TZ: Europe/Moscow
            MYSQL_TCP_PORT: 3357
        volumes:
            - "dump:/docker-entrypoint-initdb.d"
            - "./mysqld57.cnf:/etc/mysql/conf.d/custom-mysqld.cnf:cached"
    mysql-8:
        container_name: mysql-8.0
        image: library/mysql:8.0
        ports:
            - 3380:3380
        environment:
            MYSQL_ROOT_PASSWORD: 12345
            TZ: Europe/Moscow
            MYSQL_TCP_PORT: 3380
        volumes:
            - "dump:/docker-entrypoint-initdb.d"
            - "./mysqld80.cnf:/etc/mysql/conf.d/custom-mysqld.cnf:cached"
volumes:
    dump:
        driver: local
        driver_opts:
            type: none
            device: "${PWD}/Docker/mysql/dump"
            o: bind
